{
 "title": "triton",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "nv_cpu_memory_total_bytes", "legendFormat": "__auto" },
    { "expr": "nv_cpu_memory_used_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "cpu utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "nv_cpu_utilization", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "gpu memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "nv_gpu_memory_used_bytes", "legendFormat": "__auto" },
    { "expr": "nv_gpu_memory_total_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "gpu utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "nv_gpu_utilization", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "inference duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "nv_inference_request_duration_us",
     "legendFormat": "__auto"
    },
    { "expr": "nv_inference_queue_duration_us", "legendFormat": "__auto" },
    {
     "expr": "nv_inference_compute_input_duration_us",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "inference count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "nv_inference_count", "legendFormat": "__auto" },
    { "expr": "nv_inference_exec_count", "legendFormat": "__auto" }
   ]
  }
 ]
}