apiVersion: 1

datasources:
- name: prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  password:
  user:
  database: MYINFLUXDB
  basicAuth: false
  isDefault: true
  jsonData:
     httpMethod: POST
